### ISSUE TITLE
[feat] Save account information on creation

### ISSUE THREAD

**Issue by trbutler4** [keep-starknet-strange/starknet-phone#109] opened 2024-10-22 00:12 UTC
Currently, the account creation flow is just UI, and no actual account information is saved. When a user goes through the account creation flow, save their account information so that when the app is started up it takes the user directly to their account. 

Search for TODO(#109) to find where to change the code

**Comment by CollinsC1O** [comment] 2024-10-24 07:12
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hello I'm a frontend and a blockchain developer. I will love to work on this

**Comment by Mystic-Nayy** [comment] 2024-10-24 07:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a web3/frontend developer

### How I plan on tackling this issue
I will update the account creation flow to save user account information after completion, allowing for seamless login upon app startup. Implement a backend storage solution to securely save user data and modify the UI to retrieve and display this information on subsequent launches. Ensure that user data is accessible and verified during app initialization to direct users straight to their accounts.

**Comment by martinvibes** [comment] 2024-10-24 08:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
please kindly assign and i'll et to work :)

**Comment by Benjtalkshow** [comment] 2024-10-24 09:19
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To enhance the account creation flow by saving user information, we will first review the existing code, focusing on the TODO(#109) section. This involves understanding how user data is currently handled during the UI process.

Next, we'll design a secure data model for storing essential account details, such as usernames and passwords, ensuring encryption and safety. We’ll then modify the UI to connect with this backend, implementing API calls to save the user data upon account creation.

Comprehensive testing will follow, including unit, integration, and user acceptance tests to ensure functionality and security. Finally, we’ll gather feedback to optimize the user experience, allowing users to access their accounts directly upon app startup. This approach will create a seamless and secure account creation process.

**Comment by 0xdevcollins** [comment] 2024-10-24 09:36
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
To save user account information during the account creation flow, I will locate the TODO(#109) comment in the codebase and implement the logic to store user details. This could involve saving the information in a local database or shared preferences.

I will also ensure that the app retrieves this information on startup, allowing users to go directly to their accounts instead of the login screen. After making these changes, I will test the flow to ensure everything functions as intended, providing a seamless user experience.

**Comment by aniruddhaaps** [comment] 2024-10-24 12:32
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-phone).

### My background and how it can be leveraged
I am a rust dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by trbutler4** [comment] 2024-10-25 01:10
@Mystic-Nayy Hey! Please let me know if you have any questions about the issue, You can ask here or send a message in the telegram group here: https://t.me/+8G3EBNnfyS1lNzYx

**Comment by lauchaves** [comment] 2024-11-15 04:57
Hey 👋 @trbutler4 is this one available for contribution I noticed is being open for a while, if so I’d love to work on it 🚀

**Comment by trbutler4** [comment] 2024-12-12 02:51
> Hey 👋 @trbutler4 is this one available for contribution I noticed is being open for a while, if so I’d love to work on it 🚀

Hey! yes im going to go ahead and close the PR that is currently up. If you still want to work on this ill assign it

**Comment by sajalbnl** [comment] 2024-12-16 15:24
Hey @trbutler4  ,Can i work on this

**Comment by trbutler4** [comment] 2024-12-18 04:57
> Hey @trbutler4 ,Can i work on this

assigned!

**Closed** 2024-12-23 04:41 UTC
